run_name: 'test' # run directory
n_ant: 8 # number of Rx Antennas
n_user: 8 # number of Transmitted Symbols, users
SNR_start: 14 # start SNR value
SNR_step: 2 # increment of SNR values
SNR_end: 14 # last SNR value
iterations: 5 # number of iterations in the unfolded network
train_frame_size: 5000 # number of subsequent transmissions
test_frame_size: 400 # number of subsequent transmissions
train_frame_num: 10 # coherence-time block size
test_frame_num: 50 # coherence-time block size
csi_noise: 0 # number of subsequent transmissions
fading: False # whether to use fading
channel_mode: 'COST' # the channel model: set 'SED' for the Spatial Exponential Decay Channel Model, i.e. exp(-|i-j|),
# set 'Gaussian' for a Gaussian Channel, i.e. N(0,1).
# 'COST' for COST 8X8 setup.
eval_mode: 'by_word' # Type of evaluation. Per snr - 'aggregated', Per block - 'by_word'.
lr: 0.01 # learning rate
max_epochs: 60 # number of training epochs
self_supervised_epochs: 40 # number of self-supervised epochs
use_ecc: True # whether to encode with error correction codes
n_ecc_symbols: 8 # number of symbols in ecc
self_supervised: True # whether to train in an online fashion [True,False]
ber_thresh: 0.02 # threshold for self-supervised training