n_ant: 8 # number of Rx Antennas
n_user: 8 # number of Transmitted Symbols, users
snr: 12 # SNR value
iterations: 5 # number of iterations in the unfolded network
info_size: 80 # number of subsequent transmissions
train_frame_num: 50 # coherence-time block size
test_frame_num: 40 # coherence-time block size
test_pilot_size: 0 # number of subsequent pilot transmissions
fading: False # whether to use fading
linear_channel: True # whether channel is linear or not. In case it is not - a tanh function is applied.
channel_mode: 'COST' # the channel model: set 'SED' for the Spatial Exponential Decay Channel Model, i.e. exp(-|i-j|),
# 'COST' for COST 8X8 setup.
lr: 0.01 # learning rate
max_epochs: 100 # number of training epochs
self_supervised_epochs: 50 # number of self-supervised epochs
use_ecc: True # whether to use ecc (corrupted data blocks) for training, or use the genie aided blocks
n_ecc_symbols: 2 # number of symbols in ecc
ber_thresh: 0.02 # threshold for self-supervised training
change_user_only: 2 # index of single fading user
retrain_user: # index of specific user-networks that need retraining