n_ant: 4 # number of Rx Antennas
n_user: 4 # number of Transmitted Symbols, users
snr: 14 # SNR value
iterations: 5 # number of iterations in the unfolded network
info_size: 5000 # number of subsequent transmissions
train_frame_num: 50 # coherence-time block size
test_frame_num: 50 # coherence-time block size
test_pilot_size: 100 # number of subsequent pilot transmissions
fading: True # whether to use fading
channel_mode: 'SED' # the channel model: set 'SED' for the Spatial Exponential Decay Channel Model, i.e. exp(-|i-j|),
# 'COST' for COST 8X8 setup.
lr: 0.01 # learning rate
max_epochs: 100 # number of training epochs
self_supervised_epochs: 50 # number of self-supervised epochs
use_ecc: False # whether to use ecc (corrupted data blocks) for training, or use the genie aided blocks
n_ecc_symbols: 0 # number of symbols in ecc
ber_thresh: 0.02 # threshold for self-supervised training
change_user_only: # index of single fading user
retrain_user: # index of specific user-networks that need retraining